import {
  GraduationCap,
  BookOpen,
  Landmark,
  Briefcase,
  Calculator,
  Scale,
  Stethoscope,
  Microscope,
  Laptop,
  Sprout,
  Shield,
  Globe,
  Map,
  Train,
  Ship,
  Plane,
  Anchor,
  Hammer,
  Target,
  Building2,
  Users,
  Baby,
  PenTool,
  Newspaper,
  MessagesSquare,
  BadgeCheck,
  Zap,
  FileText,
} from "lucide-react";

export const ICON_LIBRARY = [
  { name: "GraduationCap", icon: GraduationCap, tags: "bcs study education" },
  { name: "BookOpen", icon: BookOpen, tags: "bcs bangla literature" },
  { name: "Landmark", icon: Landmark, tags: "bank govt politics bcs" },
  { name: "Briefcase", icon: Briefcase, tags: "job work corporate" },
  { name: "Calculator", icon: Calculator, tags: "math bank accounting" },
  { name: "Scale", icon: Scale, tags: "law judge judiciary" },
  { name: "Stethoscope", icon: Stethoscope, tags: "medical doctor health" },
  { name: "Microscope", icon: Microscope, tags: "science biology research" },
  { name: "Laptop", icon: Laptop, tags: "ict computer tech" },
  { name: "Sprout", icon: Sprout, tags: "agriculture krishi nature" },
  { name: "Shield", icon: Shield, tags: "police army defense security" },
  { name: "Globe", icon: Globe, tags: "international affairs gk" },
  { name: "Map", icon: Map, tags: "bangladesh geography" },
  { name: "Train", icon: Train, tags: "railway transport" },
  { name: "Ship", icon: Ship, tags: "navy water marine" },
  { name: "Plane", icon: Plane, tags: "airforce fly pilot" },
  { name: "Anchor", icon: Anchor, tags: "navy marine port" },
  { name: "Hammer", icon: Hammer, tags: "engineering construction" },
  { name: "Target", icon: Target, tags: "focus goal strategy" },
  { name: "Building2", icon: Building2, tags: "office company infrastructure" },
  { name: "Users", icon: Users, tags: "people social primary" },
  { name: "Baby", icon: Baby, tags: "primary school kids child" },
  { name: "PenTool", icon: PenTool, tags: "art writing drawing" },
  { name: "Newspaper", icon: Newspaper, tags: "news current affairs" },
  {
    name: "MessagesSquare",
    icon: MessagesSquare,
    tags: "viva interview speech",
  },
  { name: "BadgeCheck", icon: BadgeCheck, tags: "pass success certified" },
  { name: "Zap", icon: Zap, tags: "power electricity energy" },
  { name: "FileText", icon: FileText, tags: "general test exam" },
];

export const COLORS = [
  { name: "slate", class: "bg-slate-600" },
  { name: "gray", class: "bg-gray-600" },
  { name: "red", class: "bg-red-600" },
  { name: "orange", class: "bg-orange-600" },
  { name: "amber", class: "bg-amber-600" },
  { name: "yellow", class: "bg-yellow-500" },
  { name: "lime", class: "bg-lime-600" },
  { name: "green", class: "bg-green-600" },
  { name: "emerald", class: "bg-emerald-600" },
  { name: "teal", class: "bg-teal-600" },
  { name: "cyan", class: "bg-cyan-600" },
  { name: "sky", class: "bg-sky-600" },
  { name: "blue", class: "bg-blue-600" },
  { name: "indigo", class: "bg-indigo-600" },
  { name: "violet", class: "bg-violet-600" },
  { name: "purple", class: "bg-purple-600" },
  { name: "fuchsia", class: "bg-fuchsia-600" },
  { name: "pink", class: "bg-pink-600" },
  { name: "rose", class: "bg-rose-600" },
  { name: "black", class: "bg-black" },
];
