import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. দুটি প্রভাইডার ইম্পোর্ট করুন
import { AuthProvider } from "@/app/components/providers/auth-provider";
import { QueryProvider } from "@/app/components/providers/query-provider";

// 2. Toaster (Sonner) ইম্পোর্ট করুন
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Nesting: AuthProvider -> QueryProvider -> Children */}
        <AuthProvider>
          <QueryProvider>{children}</QueryProvider>
        </AuthProvider>

        {/* 3. Toaster কম্পোনেন্টটি এখানে অ্যাড করুন (সবার শেষে) */}
        <Toaster />
      </body>
    </html>
  );
}
